spring.application.name=EmployeeManagementSystem

spring.datasource.url=jdbc:mysql://localhost:3306/EMS
spring.datasource.username=root
spring.datasource.password=Akhil@04

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
company.name= akhilmanagementsystem
company.location=Bihar
company.email=mdtabishfiroz04@gmail.com